baseURL = "/"
languageCode = "en-gb"
title = "Jamie Magee"
theme = "hyde-x"

[pagination]
  pagerSize = 5

copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[params]
  theme = "theme-base-0c"
  tagline = "Programmer, Engineer, Problem Solver"
  truncate = false
  home = "Home"
  gravatarHash = "5a37e2531db08529192d7d323e8cecd8"
  customCSS = "/css/jamie.css"
  author = "Jamie Magee"

  # Sidebar URLS
  github = "https://github.com/JamieMagee"
  linkedin = "https://www.linkedin.com/in/jamiemagee1/"
  bluesky = "https://bsky.app/profile/jamiemagee.bsky.social"
  rss = true

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Archive"
    url        = "/blog"


[markup.highlight]
  guessSyntax = true
  lineNos = true
  lineNumbersInTable = false
  style = "github"
  tabWidth = 2

[markup.goldmark.renderer]
  unsafe= true